apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app.kubernetes.io/name: postgres-configmap
    app.kubernetes.io/version: "13"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: default
    app.kubernetes.io/managed-by: helm
data:
  10-create-user-and-dbs.sql: |
    CREATE ROLE program WITH PASSWORD 'test';
    ALTER ROLE program WITH LOGIN;
    CREATE DATABASE tickets;
    GRANT ALL PRIVILEGES ON DATABASE tickets TO program;
    CREATE DATABASE flights;
    GRANT ALL PRIVILEGES ON DATABASE flights TO program;
    CREATE DATABASE privileges;
    GRANT ALL PRIVILEGES ON DATABASE privileges TO program;